name: default

on:
  push:
    branches:
      - "main"
    paths:
    - 'build.sh'
    - '**/*.cs'
  pull_request:
    branches:
      - "main"

jobs:
  build:
    name: Running tests on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          9.x
    - name: build
      run: bash build.sh
